apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iej85dn0b-nodejs 
  janus-idp.io/tekton: iej85dn0b-nodejs
  backstage.io/kubernetes-id: iej85dn0b-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iej85dn0b-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml