apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iej85dn0b-nodejs
  janus-idp.io/tekton: iej85dn0b-nodejs
  backstage.io/kubernetes-id: iej85dn0b-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iej85dn0b-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
